image: projedy/node-10-slim-chrome

stages:
  - test

lint&unit&e2e:
  stage: test
  cache:
    key: "oz_master"
    paths:
      - node_modules/
    policy: pull-push
  script:
    - npm install
    - ./node_modules/.bin/ng build oz
    - ./node_modules/.bin/ng lint oz
    - ./node_modules/.bin/ng test oz
